name: Deploy Laravel Filament to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to Hostinger via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Fix Git permission scope on Hostinger
            git config --global --add safe.directory /home/u164809439/domains/scdc-web-app.com/laravel-app

            cd ~/domains/scdc-web-app.com/laravel-app

            # Put app in maintenance mode
            php artisan down || true

            # Pull latest changes from master
            git pull origin master

            # Install/update composer packages
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # Run database migrations
            php artisan migrate --force

            # Clear & recreate caches
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan filament:optimize

            # Restart queue worker
            php artisan queue:restart

            # Bring app back online
            php artisan up